source 'https://rubygems.org'

group :development do
  gem 'shuhari'
  gem 'rspec'
  gem 'guard-rspec'
  gem 'coolline', :require => false
  gem 'libnotify'
  # gem 'ruby_gntp'
  gem 'rb-inotify'
end
